### ISSUE TITLE
Feature request: automatically generate inheritance graph/dependency graph

### ISSUE THREAD

**Issue by elimkwan** [elimkwan/axs_clone#1]
## Prerequisite
Please try out this onboarding document (Step 1 to 4) to install and get familiar with axs.

## Steps

This is a clone of Axs main kernel, we can play with it here and prepare a pull request for it when it is ready. Basically, we would like to:
### Step 1. Generate inheritance graph for axs
Based on the python script (https://github.com/elimkwan/axs_clone/blob/graph/draw_hierarchy.py and https://github.com/elimkwan/axs_clone/blob/graph/gv_test.py) given by Leo, we can rework it into something. The current scripts work when placed in `~/axs`, then `` For a given entry, it can show the parent(s) and the parent(s) of the output entry (if there is a output entry). For example in https://github.com/krai/axs/blob/master/core_collection/bert_squad_onnxruntime_py/data_axs.json, the parent is python_script (because https://github.com/krai/axs/blob/master/core_collection/bert_squad_onnxruntime_py/data_axs.json#L2) and the parent of the output entry is base_bert_experiment(because https://github.com/krai/axs/blob/master/core_collection/bert_squad_onnxruntime_py/data_axs.json#L63). This observation is right most of the times: When you see _parent_entries at the first level of the json, the list gives the parents of the current entry; when you see _parent_entries at the deeper level of the json, the list gives the parents of the output. Ideally, for a given entry, we should be able to track who is the parents, and who are the parents of the parents etc etc.

For example, by calling the script
```
python draw_hierarchy.py {path to bert_squad_onnxruntime.py}
```
We can get something like this:
![IMG_2296](https://user-images.githubusercontent.com/36849820/231421453-8a739fcd-93db-4899-a413-5f1e97356400.jpg)
There are many different ways to visualize it better (graphviz is widely supported), open to suggestions!

### Step 2 Generate inheritance graph with more details
For a given repo/entry, it can show the parent(s) and the parent(s) of the output entry (if there is a output entry).
And it can show the functions in their code_axs.py

### Step 3. Generate dependency graph
Include dependency as well, not just capturing the parent-child relationships. Similar to something like this drawio diagram for x-qaic-private.

### Step 4. Integrate into kernels
Achieving something like this:
```
axs showgraph {repo-name}
axs showgraph {target-entry-name}
```

**Comment by sahelib25** [comment]
### Update: 
At the moment, the graph for `bert_squad_onnxruntime.py` looks something like this,
![image](https://github.com/elimkwan/axs_clone/assets/47847054/4ea2c47c-446f-43e7-819a-262334de1c4c)
### Next Steps : 
#### Issues:
1. How to access nested json object keys and values? Like, the example shown below,(`_parent_entries` from `output_file_path`)
```
"output_file_path": [ "^^", "execute", [[
        [ "get", "__record_entry__" ],
        [ "attach", [ "^", "work_collection" ] ],
        [ "plant", [ "^^", "substitute", [[
            "_parent_entries", [ "AS^IS", "AS^IS", [ "^", "byname", "base_bert_experiment" ] ],
            "tags", [ "program_output", "bert_squad" ],
            "model_name", "#{model_name}#",
            "framework", "#{framework}#",
            "output_file_name", "#{output_file_name}#",
            "desired_python_version", "#{desired_python_version}#"
         ]] ] ],
         [ "save" ],
         [ "get_path_from", "output_file_name" ]
      ]] ],
```
  
2. How to get the `_parent_entries` under `_parent_entries` i.e. to retrieve multiples parents from the `data_axs.json` file?

**Comment by elimkwan** [comment]
Hi! To answer your question, let the current entry be A:

**To find A's parents**, we can just use a in-built functions. This will return the list of A parents:
```
parents = target_entry.get("_parent_entries")
```
This [line](https://github.com/elimkwan/axs_clone/blob/master/core_collection/graph/code_axs.py#L67) currently forced us to only focus on 1 parent. Relaxing it will allow us to consider the multiple parents case.

**To find A's output's parents**, we need to use regex, like the example we coded up last time
https://github.com/elimkwan/axs_clone/blob/master/core_collection/graph/code_axs.py#L117
```
obj = ['_parent_entries', ['AS^IS', 'AS^IS', ['^', 'byname', 'base_bert_experiment']], 'tags', ['program_output', 'bert_squad'], 'model_name', '#{model_name}#', 'framework', '#{framework}#', 'output_file_name', '#{output_file_name}#', 'desired_python_version', '#{desired_python_version}#']
    item = find_key(obj, "byname")
    ..
key == "_parent_entries" and re.search(r"^\[(?:'|\")_parent_entries(.*)", str(obj)):
```
This regex syntax only find the first parent, please check on its [documentation](https://docs.python.org/3/library/re.html) on how to expand it. (More regex resources on [here](https://regex-generator.olafneumann.org/?sampleText=2020-03-12T13%3A34%3A56.123Z%20INFO%20%20%5Borg.example.Class%5D%3A%20This%20is%20a%20%23simple%20%23logline%20containing%20a%20%27value%27.&flags=i) and [here](https://regexr.com/) and much more ... ) There are 3 cases:
1. When A's output has 1 parents
```
"_parent_entries", [["^", "byname", "base_bert_loadgen_experiment"]],
```
2. When A's output has 2 parents
```
"_parent_entries", [["^", "byname", "base_bert_loadgen_experiment"], ["^", "byname", "base_qaic_experiment"]],
```
3. When A's output has 2 parents  with delays `AS^IS` (for delaying intepretation)
```
"_parent_entries", ["AS^IS" , "AS^IS", [["^", "byname", "base_bert_loadgen_experiment"], ["^", "byname", "base_qaic_experiment"]]],
```
Note that when copying examples from axs data json, they are in double quote`"`, as shown above, but after loading it into python and printing it out, they become single quote `'`.

@sahelib25 Please look into how to expand the graph entry to handle the case when:
- A has multiple parents
- Any of A's parents has multiple parents
- A's output has multiple parents
- A's output's has multiple parents and with the delay sign in front of it

Thanks!

**Comment by sahelib25** [comment]
Hi @elimkwan!
Please find attached the image, where the 4 issues have been addressed:

- A has multiple parents
- Any of A's parents has multiple parents
- A's output has multiple parents
- A's output's has multiple parents and with the delay sign in front of it

`AXS` command:
```
axs byname graph , draw bert_squad_onnxruntime_py
```
To implement the scenarios of multiple parents of a node/output_node , I have made few modifications to the `data_axs.json` file of `bert_squad_onnxruntime_py`, which are shown below:

#### Scenario : A has multiple parents / Any of A's parents has multiple parents
```
 "_parent_entries": [ [ "^", "byname", "python_script" ] , [ "^", "byname", "base_imagenet_experiment" ]],
```
#### Scenario : A's output has multiple parents / A's output's has multiple parents and with the delay sign in front of it
```
"_parent_entries", [[ "AS^IS", "AS^IS", [ "^", "byname", "base_bert_experiment" ] ], [ "AS^IS", "AS^IS", [ "^", "byname", "base_bert_loadgen_experiment" ] ]],
```
![image](https://github.com/elimkwan/axs_clone/assets/47847054/b86abae1-d010-4fe1-a427-8a0c2f2bd113)

Let me know if you have any other features to add to it. Thanks!

**Comment by elimkwan** [comment]
Hi @sahelib25 , functionality wise it seems great!

Next step:
- making it visually appealing (https://github.com/elimkwan/axs_clone/issues/2)
- sync with current axs kernals (https://github.com/elimkwan/axs_clone/issues/3)
- test it works for all axs entry (If not all, at least most of them) (https://github.com/elimkwan/axs_clone/issues/4)
