### ISSUE TITLE
Improving the visual of the generated dependency graph

### ISSUE THREAD

**Issue by elimkwan** [elimkwan/axs_clone#2]
For clarity reasons, can we have some colour scheme, for example, 

Group A
bert_squad_onnxruntime_py: red
bert_squad_onnxruntime_py 's parents: light red

Group B
bert_squad_onnxruntime_py 's output: blue
bert_squad_onnxruntime_py 's output's parent: light blue

And group A and B can be separated with a dotted line on the graph?

**Comment by sahelib25** [comment]
Here is the output image after grouping the nodes, and colouring using the above conditions:

- Group A

bert_squad_onnxruntime_py: red
bert_squad_onnxruntime_py 's parents: light red

- Group B

bert_squad_onnxruntime_py 's output: blue
bert_squad_onnxruntime_py 's output's parent: light blue

and separating using clusters and dotted lines,
 ![image](https://github.com/elimkwan/axs_clone/assets/47847054/2f0a37c9-6059-4177-8be3-e13dcb3929f5)

**Comment by elimkwan** [comment]
@sahelib25 Looking good! Perhaps rename Group A and B as some more meaningful names? Like 
- Group A -> Entry and Its Parent(s)
- Group B -> Parent(s) of the Output Entry

Otherwise all good!

**Comment by sahelib25** [comment]
Thanks! Group A and B are renamed accordingly,
![image](https://github.com/elimkwan/axs_clone/assets/47847054/23c959f3-ffaa-482b-b0d6-52dd11a1ef9d)
